<h1>Tensorboard-Visualize Graph</h1>
<p style="font-size:20px">We will introduce Tensorboard which is able to display nice interactive visualizations in your web browser. We will start from basics. In this tutorial, we will show how to visualize the graph you create. In the next tutorial, you will learn how to show the statistics of your training model in Tensorboard.

In [1]:
import tensorflow as tf

<p style="font-size:20px">The first step is to tweak your program a bit so it writes the graph definition or some training stats to a log directory that TensorBoard will read from. You may need to use a different log directory every time you run your program, or else TensorBoard will merge stats from different runs, which may mess up the visualizations.

<p style="font-size:20px">The simplest solution for this is to include a time-stamp in the log directory name. In the following code, we define the log directory:

In [2]:
from datetime import datetime
now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
root_logdir = "tf_logs"
logdir = "{}/run-{}/".format(root_logdir,now)

<p style="font-size:20px">Next, we will create a simple addition program like what we show in the basics tutorial:

In [3]:
x = tf.constant([1,2,3,4],name='x')
y = tf.constant([5,6,7,8],name='y')
z = tf.constant([9,10,11,12],name='z')
result = tf.add(x,y)

<p style="font-size:20px">Now we need to create a <b>FileWriter</b> that you will use to write the graph to the logfiles in the log directory. The first parameter indicates the path of the log directory. The second parameter is the graph you want to visualize.

In [4]:
file_writer = tf.summary.FileWriter(logdir,tf.get_default_graph())

<p style="font-size:20px">Next, we will simply do the same thing as before, create the session and run:

In [5]:
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(z))
    print(sess.run(result))

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[ 6  8 10 12]


<p style="font-size:20px">Finally, you wnat to close the <b>FileWriter</b> at the end of the program:

In [6]:
file_writer.close()

<p style="font-size:20px">Now, open your terminal and go to your working directory, you will see a <b>tf_logs</b> directory. And inside that directory, you will see a <b>run-20190329210258</b> directory. Inside this directory, you will see an <b>events</b> file. Now you can fire up the TensorBoard server by doing the following command:

<p style="font-size:20px">$tensorboard --logdir=path/to/log-directory

<p style="font-size:20px">You will see the following information popped up:

<p style="font-size:20px">"Starting TensorBoard on port 6006
<p style="font-size:20px">(you can navigate to http://0.0.0.0:6006)"

<p style="font-size:20px">Next, open a browser and go to that URL, welcome to TensorBoard!

<p style="font-size:20px">You will see the interface like the figure</p>
<img src="figures/tensorboard_1.png">

<p style="font-size:20px">Here you can visualize the graph you create. Pay attention to several things:
<p style="font-size:20px">1. when you define the Constant and operation,you define the nodes' names. Here we didn't define the name for <b>tf.add</b> so Tensorflow will use the default name "Add". It'd be good habit to name everything in the graph to avoid confusion.
<p style="font-size:20px">2. We see there is no "z" node shown in Tensorboard. That's because in Tensorboard, it requires the node has at least one math operation to visualize. You can't see the constant node if you don't use it with other nodes. We can see nodes "x" and "y" are used to compute the "Add" node. So they show up in the Tensorboard.